### PR TITLE
[WIP] Fix UI/UX

### LINKED ISSUE #50: Fix UI/UX bugs
This is a list of UI/UX bugs to fix:

## Across steps
**General**
- [ ] General left & right margins should be 24px and all elements should be aligned to this
- [ ] Step title should be font-size: 22p; line-height: 28px;
- [x] Font should be [Inter UI](https://rsms.me/inter/)

**Input fields**
- [ ] Input field right margin should be 24px (now is too closed to the right border)
- [ ] Input field should have border-radius: 8px;
- [ ] Input field label color should be Black (see color variables in Figma)
- [ ] Input field label should be font-size: 15px; line-height:22px; 
- [ ] Space between step title and input field label should be 24px
- [ ] Input field should be height: 52px;
- [ ] Placeholder should be aligned in the center (vertically)
- [ ] Char counter label should be font-size: 12px;
- [ ] Char counter right padding should be 24px
- [ ] Padding for the multi-line input field should be 14px (distance between text inside the input field and the borders of the input field)

**Call to action**
- [ ] Call to action white container's height should be 52px
- [ ] CTA label should be font-size: 15px; line-height:22px; (now is too small)

## Step 3 - Add options
- [ ] Plus (+) icon is missing (broken in Chrome). 
- [ ] "New option" modal should slide from the bottom
- [ ] **[UX]** "New option" modal: "Save" button should be disabled until user enter option title and description
- [ ] "New option" modal: Close icon should be aligned to the left 
- [ ] "New option" modal: Close icon should be the provided icon (see Figma)
- [ ] "New option" modal: "Save" label should be font-size: 15px; line-height:22px; 
- [ ] **[UX]** "Poll description" input field label should say "Option description"
- [ ] **[UX]** When user taps on a created option in the list, the modal should open with pre-loaded data, ready to edit, with "Save" enabled.
- [ ] Header should be fixed (see Figma prototype)
- [ ] **[UX]** Options should be ordered chronologically (latest first). By this, when you create a new one, you don't need to scroll all the way down to see what you just created and we give the user a sense of feedback/completion of the task of adding an option. 

## Step 4 - Set date/time
- [ ] **[UX]** CTA should say "Review" instead of "Next".

## Step 5 - Review
- [ ] Poll title (not page title) should be font-size: 17px; line-height: 24px;
- [ ] Poll description text should be font-size: 15px; line-height:22px; 
- [ ] Distance between poll description and date card should be 32px
- [ ] Time/Date card: height should be 144px (need to adjust text and spaces inside, see next items)
- [ ] Time/Date card: border should be #EEF2F5
- [ ] Time/Date card: "Poll starts" and "Poll ends" titles should be font-size: 15px; line-height:22px; 
- [ ] Time/Date card: dates/time text should be font-size: 15px; line-height:22px; font-weight: 600; (semibold)
- [ ] "Options" grey label should be font-size: 15px; line-height:22px; 
- [ ] Distance between "Options" grey label and first option should be 8px (is too close now)
- [ ] Options cards: Height should be 72px (need to adjust text and spaces inside, see next items)
- [ ] Options cards: Paddings should be 16px 
- [ ] Options cards: Option title should be font-size: 15px; line-height:22px; font-weight: 600; (semibold)
- [ ] Options cards: Option grey description should be font-size: 13px;
- [ ] Options cards: Distance between option cards should be 12px
- [ ] CTA should say "Sign to confirm" not "Sign To Confirm" (no capitalization)

[Designs on Figma](https://www.figma.com/file/L1qhHMiZr5dTVdDxrjsbxHYp/Voting-Dapp?node-id=1530%3A759)

### PR DESCRIPTION
**Pull request by PumpkingWok**
#### General
- [X] General left & right margins should be 24px and all elements should be aligned to this
- [X] Step title should be font-size: 22p; line-height: 28px;
- [X] Font should be Inter UI

#### Input fields

  - [X] Input field right margin should be 24px (now is too closed to the right border)
  - [X] Input field should have border-radius: 8px;
  - [X] Input field label color should be Black (see color variables in Figma)
  - [X] Input field label should be font-size: 15px; line-height:22px;
  - [X] Space between step title and input field label should be 24px
  - [X] Input field should be height: 52px;
  - [X] Placeholder should be aligned in the center (vertically)
  - [X] Char counter label should be font-size: 12px;
  - [X] Char counter right padding should be 24px
  - [X] Padding for the multi-line input field should be 14px (distance between text inside the input field and the borders of the input field)

#### Call to action

- [X] Call to action white container's height should be 52px
- [X] CTA label should be font-size: 15px; line-height:22px; (now is too small)

### Step 3 - Add options
- [X] Plus (+) icon is missing (broken in Chrome).
- [X] "New option" modal should slide from the bottom
- [X] [UX] "New option" modal: "Save" button should be disabled until user enter option title and description
- [X] "New option" modal: Close icon should be aligned to the left
- [X] "New option" modal: Close icon should be the provided icon (see Figma)
- [X] "New option" modal: "Save" label should be font-size: 15px; line-height:22px;
- [X] [UX] "Poll description" input field label should say "Option description"
- [X] [UX] When user taps on a created option in the list, the modal should open with pre-loaded data, ready to edit, with "Save" enabled.
- [X] Header should be fixed (see Figma prototype)
- [X] [UX] Options should be ordered chronologically (latest first). By this, when you create a new one, you don't need to scroll all the way down to see what you just created and we give the user a sense of feedback/completion of the task of adding an option.
### Step 4 - Set date/time
- [X] [UX] CTA should say "Review" instead of "Next".
### Step 5 - Review
- [X] Poll title (not page title) should be font-size: 17px; line-height: 24px;
- [X] Poll description text should be font-size: 15px; line-height:22px;
- [X] Distance between poll description and date card should be 32px
- [X] Time/Date card: height should be 144px (need to adjust text and spaces inside, see next items)
- [X] Time/Date card: border should be #EEF2F5
- [X] Time/Date card: "Poll starts" and "Poll ends" titles should be font-size: 15px; line-height:22px;
- [X] Time/Date card: dates/time text should be font-size: 15px; line-height:22px; font-weight: 600; (semibold)
- [X] "Options" grey label should be font-size: 15px; line-height:22px;
- [X] Distance between "Options" grey label and first option should be 8px (is too close now)
- [X] Options cards: Height should be 72px (need to adjust text and spaces inside, see next items)
- [X] Options cards: Paddings should be 16px
- [X] Options cards: Option title should be font-size: 15px; line-height:22px; font-weight: 600; (semibold)
- [X] Options cards: Option grey description should be font-size: 13px;
- [X] Options cards: Distance between option cards should be 12px
- [X] CTA should say "Sign to confirm" not "Sign To Confirm" (no capitalization)

Fixes #50

### CODE REVIEW

**Comment by PumpkingWok** [comment]
Hi @richard-ramos,
I would like to ask you a question, what do you mean with `Step title` ? 
The title that changes at every step (Poll Name, Poll Description, ecc..) or the title fixed (Create a Poll).
I asked it because `general` says that stepTitle should be font-size of 22px but in `Input Fields` the label should be 15px.

**Comment by richard-ramos** [comment]
Step Title refers to the fixed title `Create a Poll`
The title that changes at each step is the input field label (15px)

**Comment by PumpkingWok** [comment]
Hi @richard-ramos,
I have another question regard the first task of Step 3.
I'm testing it locally using Chrome and i can see the plus (+) icon when i want add options, do you mean it ?
Thanks

**Comment by richard-ramos** [comment]
1. There's the possibility that I had fixed that case before. If you're able to see the (+) in both desktop and mobile browsers, you can ignore that task.
2. I think this task refers to the padding the body should have.

**Comment by PumpkingWok** [comment]
Hi @richard-ramos,
> 2. I think this task refers to the padding the body should have.

Padding or margin ?

Questions regard tasks:
 - `"New option" modal: Close icon should be the provided icon (see Figma)`, i looked to Figma demonstration and i think that it uses the same icon (x-close.svg)
- `[UX] When user taps on a created option in the list, the modal should open with pre-loaded data, ready to edit, with "Save" enabled.`, I tested and It should already have this behavior.

**Comment by PumpkingWok** [comment]
Hi @richard-ramos,
Thank you for the reply.

0. I added padding.
1. Done.
2. I'm testing it only on desktop, is there an easy way to test on mobile ? 
3. For now i resolve it in another way, i have implemented the custom styles directly in js.
4. Ok, i understood.Sorry, i'm looking to resolve it. 

I know there are some issues for now, mostly in input fields but i committed all list so you can test it when you have free time. If you prefer different implementations in some point i can change it without problems, thanks in advance.

**Comment by PumpkingWok** [comment]
Hi @richard-ramos,
I'm trying to fix few issues.

-`General left & right margins should be 24px and all elements should be aligned to this`
I tried to set the body left and right padding, but it resizes the bottom `buttonNav` and the top `progressBar` too. In Sigma demonstration they remain to width 100%. I think that it is necessary to modify the DOM.

-`Input field right margin should be 24px (now is too closed to the right border)`
Do you mean the right margin of `div` that containt all textarea ? Not inside every row ?
In `Create Poll` (first step) it is a multiline textarea but in Sigma it seems to be only a one row textarea. does it make sense ?

Thanks

**Comment by richard-ramos** [comment]
> I'm testing it only on desktop, is there an easy way to test on mobile ?

What I do is first, execute `embark upload testnet` to upload the project to IPFS
Then, I execute `ipfs daemon` in another terminal, and finally, navigate to the URL returned by the upload process using the Status App (https://ipfs.infura.io/........).

**Comment by PumpkingWok** [comment]
Hi @richard-ramos,
I finished all tasks, for few tasks there could be other implementations, let me know for any doubt and clarification, i can edit the code without problems.
I tested it on desktop for now, i'm having issue to test it on mobile.
Should i be able to create some test tokens from mobile too, right ?
In any case `embark upload tested` i tested the Dapp from both localhost and infura but i can't access to poll creation page because i don't have token, i have to switch to ropsten.
Thanks in advance.

**Comment by richard-ramos** [comment]
Hi, @PumpkingWok ,  good work!  Just a few fixes and we're done with this PR :)

---
* **General left & right margins should be 24px and all elements should be aligned to this**
Image1
> Current width is 44px instead of 24px. 

---
*   **Input field right margin should be 24px (now is too closed to the right border)**
new-option
> Besides the right margin being 44px instead of 24 (this happens in different steps too),  the text-area is not aligned with the other input field.   (this is inside the "Add option" dialog

---
* In Review, **Distance between poll description and date card should be 32px**
height32
Height is ~57px instead of 32.

**Comment by PumpkingWok** [comment]
Hi @richard-ramos,
Thank you for the reply.

> Current width is 44px instead of 24px.

The other 20 px are padding of #votingDapp div.section, already edited before my commits in `styles.css`, I thought that i had to add 24 px more of margin, not create a total margin of 24px.
In this case, Do I have to add only 4px to complete the margin ?

> In Review, Distance between poll description and date card should be 32px

I'm sorry, i have left 2 `<br>` into the code. i'm going to commit the fix

> Besides the right margin being 44px instead of 24 (this happens in different steps too), the text-area is not aligned with the other input field. (this is inside the "Add option" dialog

There is a padding of 24px in options Textfields. I'm looking to fix the width of the bottom TextField.
Let me know how you prefer to do it, regard the length of margins.

**Comment by richard-ramos** [comment]
1. I think adding the 4px would work. 
2. Cool, it will be an easy fix then :)
3. I'm okay with any fix involving css margin/paddings, as long as the space between the inputs and the  border is 24px.

**Comment by PumpkingWok** [comment]
Hi @richard-ramos,
I have just committed the last fixes, it should be ok now.
Let me know if there are other issues.
Thanks in advance.

**Comment by richard-ramos** [comment]
Reviewed and approved!  thank you @PumpkingWok !

**Comment by PumpkingWok** [comment]
Hi @richard-ramos,
Thank you very much, feel free to contact me for any issue.
Have a nice day !!

**Pull request merged**
