### PR TITLE
[WIP] Fix some UI/UX bugs

### LINKED ISSUE #48: Fix UI/UX bugs
This is a list of UI bugs to fix:

captura de pantalla 2018-12-05 a la s 4 50 55 p m

**General screen**
- [ ] General left and right margins should be 24px (now is 20px)
- [ ] Right margin for the "create poll" icon should be 24px (it should be right aligned with the rest of the elements in the page)
- [ ] Page title should be font-size: 22p;  line-height: 28px;
- [ ] Space between title and Org description text should be 24px
- [ ] Org description text should be font-size: 15px; line-height: 22px;
- [ ] "Open polls"/"Closed polls" grey titles should be font-size: 12px, letter-spacing: 1px;

**Poll cards**
- [ ] Margins on cards should all be 16px (bottom margin is now 24px)
- [ ] Card title should be font-size: 17px; line-height: 24px;
- [ ] "Closes in..." label should be font-size: 12px;  font-weight: 600; letter-spacing: 1px; 
- [ ] "Closes in..." badge should grow horizontally with content to support translation (width: fit-content; padding: 5px 10px;)
- [ ] Space between date badge and stats should be 16px
- [ ] "Votes/Total SNT" labels should be font-size:14px; line-height: 22px;
- [ ] Space between stats and "Vote now" CTA should be 16px
- [ ] "Vote now" CTA should be font-size: 15px; line-height: 22px;
- [ ] Apply same cards fixes to the complete list of open polls
- [ ] Apply same cards fixes to the complete list of closed polls

**Buttons**
- [ ] Button height should be 44px (now is 35)
- [ ] Button label should be font-size: 15px; line-height: 22px;
- [ ] Apply same button fixes to buttons in the complete list of open polls
- [ ] Apply same button fixes to buttons in the complete list of closed polls
- [ ] Space between first button and "closed polls" section should be 32px

[Designs on Figma](https://www.figma.com/file/L1qhHMiZr5dTVdDxrjsbxHYp/Voting-Dapp?node-id=1611%3A416)

### PR DESCRIPTION
**Pull request by anshumanv**
Fixes #48 

Will be pushing more commits to this branch and will ask for review/help once needed. 👍 

General screen

- [x]   General left and right margins should be 24px (now is 20px)
- [x]   Right margin for the "create poll" icon should be 24px (it should be right aligned with the rest of the elements in the page)
- [x]   Page title should be font-size: 22p; line-height: 28px;
- [x]   Space between title and Org description text should be 24px
- [x]   Org description text should be font-size: 15px; line-height: 22px;
- [x]   "Open polls"/"Closed polls" grey titles should be font-size: 12px, letter-spacing: 1px;

Poll cards
- [x]  Margins on cards should all be 16px (bottom margin is now 24px)
- [x]   Card title should be font-size: 17px; line-height: 24px;
- [x]   "Closes in..." label should be font-size: 12px; font-weight: 600; letter-spacing: 1px;
- [x]   "Closes in..." badge should grow horizontally with content to support translation (width: fit-content; padding: 5px 10px;)
- [x]   Space between date badge and stats should be 16px
- [x]   "Votes/Total SNT" labels should be font-size:14px; line-height: 22px;
- [x]   Space between stats and "Vote now" CTA should be 16px
- [x]   "Vote now" CTA should be font-size: 15px; line-height: 22px;
- [x]   Apply same cards fixes to the complete list of open polls
- [x]   Apply same cards fixes to the complete list of closed polls

Buttons
- [x]   Button height should be 44px (now is 35)
- [x]   Button label should be font-size: 15px; line-height: 22px;
- [x]   Apply same button fixes to buttons in the complete list of open polls
- [x]   Apply same button fixes to buttons in the complete list of closed polls
- [x]   Space between first button and "closed polls" section should be 32px

### CODE REVIEW

**Comment by anshumanv** [comment]
@richard-ramos iterated over the issues and fixed them, please see. 😄 

Please let me know if any changes are needed or if I missed something.

**Comment by richard-ramos** [comment]
Good work.  These changes are still missing. I still haven't tested this on mobile. Will do that at the end of the day but probably it will be okay :)

**General**
* Right margin for the "create poll" icon should be 24px (it should be right aligned with the rest of the elements in the page)
* Space between title and Org description text should be 24px


**Buttons**
* Button label should be font-size: 15px; line-height: 22px;

**Comment by anshumanv** [comment]
Hey @richard-ramos, thanks for the review. 😄 

Fixed 🎉

**Comment by anshumanv** [comment]
Fixed the conflicts @richard-ramos 😄 🎉

**Comment by richard-ramos** [comment]
good job! :100:

**Pull request merged**
