### PR TITLE
Add linting rules, with husky and prettier

### LINKED ISSUE #58: Setup prettier and precommit hooks to lint all files before each commit and have consistent coding style
All files are linted improperly and have weird spacing/tabs at places.

This will make sure all files are linted properly as per the linting rules before each commit and so we have consistent coding style.

I'll be able to do this 😄 
Planning to use prettier, husky and lint-staged to get this done.

Potential bounty @richard-ramos @StatusSceptre ? 🤔

### PR DESCRIPTION
**Pull request by anshumanv**
Fixes #58

### CODE REVIEW

**Comment by anshumanv** [comment]
@richard-ramos, please review

**Comment by anshumanv** [comment]
There are still a lot of eslint errors which I think I should solve in another bounty as it'll be very time-consuming.

image

Removed the eslint check from from precommit hook for now

**Comment by richard-ramos** [comment]
Hey @anshumanv 
I guess prettier was responsable for changing the format of the JSX content, right?  Is it possible to disable the `{' '}` it adds ?

**Comment by richard-ramos** [comment]
> There are still a lot of eslint errors which I think I should solve in another bounty as it'll be very time-consuming.
Removed the eslint check from from precommit hook for now

Yeah, the eslint errors are out of scope since it would take ages to fix that. I think we can apply the boy scout rule for future bounties: if anyone needs to modify a particular file to complete the bounty they're working on, eslint problems for that file need to be solved as well :)     

Except for the {' "}, code looks good, so hopefully you can disable that :).  I'll test the application during the course of today to see that nothing broke with the code formatting. Once that's done, I'll approve the PR.

Good work!

**Comment by anshumanv** [comment]
> Hey @anshumanv
I guess prettier was responsable for changing the format of the JSX content, right? Is it possible to disable the `{' '}` it adds ?

Thanks for the review @richard-ramos 😄 I think it's coming from one of the recommended configs which we're using, not sure which one so won't be possible to over-write also I think it makes sense to clearly denote spaces in the text as `{' '}` 🤔 which won't be to clearly visible when there's just space. What do you think?

**Comment by richard-ramos** [comment]
> I think it's coming from one of the recommended configs which we're using, not sure which one so won't be possible to over-write also I think it makes sense to clearly denote spaces in the text as `{' '}`  which won't be to clearly visible when there's just space. What do you think?

There are some code where it's not really necessary, but, ok,  it's such a small thing to be finicky about that it's not worth exploring :)   I'll accept the PR.

**Pull request merged**
