### PR TITLE
Add infinite scroll calendar to Poll Schedule component

### LINKED ISSUE #51: Apply an integrated calendar for selecting dates
## Problem
In the date selection step (step 4 of the flow) we are using a material design date selection control. For a better experience, we should apply a calendar that is more integrated with the flow and UI.

## Actual implementation
captura de pantalla 2018-12-05 a la s 6 12 09 p m

## Expected results
Original design applied:
4 - dates - start

[Designs on Figma](https://www.figma.com/file/L1qhHMiZr5dTVdDxrjsbxHYp/Voting-Dapp?node-id=1528%3A709)

### PR DESCRIPTION
**Pull request by anshumanv**
Fixes #51 

Adding infinite scrolling date picker for poll schedule component.
I've used react infinite calendar as it's a really rich component with all the required tooling and customizations with support for handling all events.

Ref - https://github.com/status-im/snt-voting/issues/51#issuecomment-449633184

### CODE REVIEW

**Comment by anshumanv** [comment]
@richard-ramos just wanted to have your view on this. 😄 

I've been working on it and exploring the bundle size as I progressed and came to realize that the library used in this PR is greatly optimized which only makes up a 2.3% part of node modules - 
image

While even the libraries for handling date time (`date-fns`) takes up 2.1%!
image
react-bootstrap takes up 5.5%! which really bloats it.
image

even the font bloats it by 5.6% 
image

And then there's material ui which makes up to 6.1% which is really heavy(think we should opt for a lighter UI library in case mobile devices are the major audience)
image

Coming to the present solution of date picker i.e. material ui date picker used to take up 1.4% 
image so that will be gone so we're effectively left with 0.9 % which would not even be noticable IMO

So that's for the statistics, as per the feature it provides, customizability and extensibility with good styling and helpers I think it's a very favourable tradeoff that we should go for. 

And to *greatly* reduce the bloat we should get rid of `react-bootstrap` as it's a major bloater whithout any extensive use and has really less instances, as we're using material-ui we should opt to use it's components in place of components used from `react-bootstrap` which are anyways very few - 
image

I'll help in getting rid of it which would greatly reduce the bloat! (5.5%) in a separate PR, let me know what you think about this deduction. 😄

**Comment by richard-ramos** [comment]
this is a really good analysis, @anshumanv! thank you!
Based on it, I'm okay with having the goal of the bounty to use the infinite calendar component + PR to reduce the bloat. What do you think, @StatusSceptre?

Good catch about the roboto font being used. The font that this project should be using is `Inter UI`

**Comment by anshumanv** [comment]
Thanks for the review, appreciate it! 😄 

I'll help reduce the bloat by replacing the fonts and react-bootstrap in a separate pr/bounty and will send one soon! 😄 🎉

**Comment by StatusSceptre** [comment]
Sounds good! @richard-ramos

**Comment by anshumanv** [comment]
@richard-ramos, I'll be sending another PR asap, meanwhile, can you merge this so no merge conflicts occur? 😄

**Comment by richard-ramos** [comment]
Hey, don't worry :) we can always rebase the changes later once all PRs are complete!

**Comment by anshumanv** [comment]
Yes @richard-ramos, please add your review. 👍 💯

**Comment by anshumanv** [comment]
@richard-ramos thanks for reviewing, fixed things you mentioned. 👍

**Comment by richard-ramos** [comment]
There's a difference between the current implementation and the figma design for the timepicker.
timepicker

A package I did look at previously for this functionality is this one: https://www.npmjs.com/package/react-mobile-picker-scroll  .  I think this component inside a material-ui dialog should do the trick.

**Comment by anshumanv** [comment]
Hey @richard-ramos 👋 

Thanks for your patience and providing guidance throughout to help me progress, added the time picker as you specified, please see. 😄

**Comment by richard-ramos** [comment]
Hey, just reviewed this :) we're almost there, dude!
I uploaded the site to IPFS pointing to testnet so you're able to see the same things as I am:
https://ipfs.infura.io/ipfs/QmV2GfAvWosmvV2UyHvb6i1cSzgqe5UGAn2kDMKoarvpz4/#/
If you need STT to be able to test this on mobile, once you connect to ropsten, you can select "Status Test DApp" in the list of dapps. (it's the last element of the list).

# Testing in the status app in a mobile device
screenshot_20190115-133130_status

* The width of the dialog is not correct. The design has a wider dialog
* I'm not able to see AM/PM  
* The "Save" button is not the same as that used in the design
* The "Edit Time" link is too close to the bottom border.
* Also, this is something that happens in mobile, when I scroll the time, the background website scrolls along with it
* The today button in the calendar has an /\  button that is overlapping the "Today" text

On desktop, the calendar is not taking the full available vertical space, and same observations regarding design.
screenshot from 2019-01-15 13-44-35

**Comment by anshumanv** [comment]
Thanks for the detailed review and deployment @richard-ramos 😄 

Fixed stuff you mentioned (I believe)

> If you need STT to be able to test this on mobile, once you connect to ropsten, you can select "Status Test DApp" in the list of dapps. (it's the last element of the list).

Not able to get what you meant by this 😅 

> The width of the dialog is not correct. The design has a wider dialog

Fixed, on desktop, limited it to a certain max width

> I'm not able to see AM/PM

Not sure about this, visible in mine, can you please recheck?

> The "Save" button is not the same as that used in the design

Made the design consistent

> The "Edit Time" link is too close to the bottom border.
Fixed

>Also, this is something that happens in mobile, when I scroll the time, the background website scrolls along with it.

Should be fixed as not happenning with mine anymore

> The today button in the calendar has an /\ button that is overlapping the "Today" text

Removed it, was unsure about it, let me know if it's needed so I'll add it back. 😄 

Desktop
image

Mobile
image

**Comment by richard-ramos** [comment]
good job! :100:

**Comment by anshumanv** [comment]
Thanks so much for helping me throughout! @richard-ramos 😄 

@StatusSceptre submitted work on gitcoin - https://gitcoin.co/issue/status-im/snt-voting/51/2035 🎉 ✨

**Pull request merged**
