### PR TITLE
Add support for Ledger

### LINKED ISSUE #1: Integrate Ledger Library
### User Story
As a front-end developer, 
I want to create a "connect to ledger" button which will allow a user to a sign transactions and pay GAS fees from their ledger wallet, 
So that users may use their ledger wallet on the SNT voting Dapp. 

### Description
*Type*: Feature 

*Summary*: 
We know that holders of SNT will have their SNT in a hardware wallet. Luckily metamask supports Tezors so we know with a fairly good degree of certainty that a seamless integration of Ledger wallets will cover a large amount of SNT holders. 

This task is to integrate the Ledger libraries http://ledgerhq.github.io/ledgerjs/docs/#eth and create a "connect with Ledger" button in the top right header which will connect to a users ledger device. 

Library found here: 
https://github.com/LedgerHQ/ledgerjs/blob/master/packages/create-dapp/template/src/wallets.js

#### Exit Criteria 
The expected behavior that a user may tap on "connect with ledger", select the account of their choice and use his/her ledger to complete a transaction on the dapp.

### PR DESCRIPTION
**Pull request by StevenJNPearce**
Fixes #1 
Some notes:

Ledger doesn't provide valid signature with chainId > 0xff (i.e. ganache-cli).
You will need to set rpcHost to send the transactions on mainnet.
I couldn't get web3-provider-engine to work, maybe bugs in the ledger implementations: this doesn't matter.
App must be served over Https. u2f doesn't work with http.
Maybe the UX could be better? You can try it and provide any input you have.

### CODE REVIEW

**Comment by Graeme-Code** [comment]
Hi @StevenJNPearce , thanks for this and the notes, will test shortly and give feedback. Cheers

**Comment by StevenJNPearce** [comment]
I've just tried out Metamask's newly launched ledger integration and I'd actually recommend closing this and letting users use that instead - Metamask has a more mature UX that offers some features that would take a fair bit of work to replicate e.g. gas price oracle, transaction fee estimation in USD, transaction history list, coinbase + shapeshift integration, resend transaction when gas price is too low.

**Comment by Graeme-Code** [comment]
@StevenJNPearce yeah, it does make this work kinda redundant...Working on getting a developer to review the PR

**Comment by Graeme-Code** [comment]
@StevenJNPearce I'm running into issues testing this on my local machine. Would you mind letting me know the steps you took to test the integration? After cloning your repo and running "embark run" I don't get the UI when going to localhost:8000

**Comment by StevenJNPearce** [comment]
> @StevenJNPearce I'm running into issues testing this on my local machine. Would you mind letting me know the steps you took to test the integration? After cloning your repo and running "embark run" I don't get the UI when going to localhost:8000

As I mentioned in the notes above, it should be served over HTTPS, so with embark run you will need to generate some certificates and modify embark/lib/modules/webserver/server.js to serve HTTPS. However the UI should still load without this... do you see any error in the embark console, or in your browser's developer console when going to localhost:8000?

**Comment by andytudhope** [comment]
Hey @StevenJNPearce I don't see those "notes above"? Could you provide exact steps to test this PR?

**Comment by StevenJNPearce** [comment]
@andytudhope 
1) Clone & npm install
2) Generate ssl cert + key
3) Modify embark dev server to support https, here is my implementation: https://gist.github.com/StevenJNPearce/df2a2e91c67d54005534c667c5c933b1
4) Change wsport in blockchain.json from 8546 to 8545 
5) `embark simulator` & `embark run` using the modified embark.
6) Open app on whatever port you are serving https, connect ledger & unlock, click connect to Ledger button.

**Comment by andytudhope** [comment]
Ok amazing, I can confirm this works @StevenJNPearce @Graeme-Code 

There is one small UI issue I am getting once my ledger accounts show up, though:

```
dapp.js:24803 Warning: Each child in an array or iterator should have a unique "key" prop.

Check the top-level render call using <WithStyles(List)>. See https://fb.me/react-warning-keys for more information.
    in WithStyles(ListItem)
    in LedgerAccountList (created by WithStyles(LedgerAccountList))
    in WithStyles(LedgerAccountList)
    in div (created by Toolbar)
    in Toolbar (created by WithStyles(Toolbar))
    in WithStyles(Toolbar)
    in header (created by Paper)
    in Paper (created by WithStyles(Paper))
    in WithStyles(Paper) (created by AppBar)
    in AppBar (created by WithStyles(AppBar))
    in WithStyles(AppBar)
    in div
    in ButtonAppBar (created by WithStyles(ButtonAppBar))
    in WithStyles(ButtonAppBar)
    in div
    in Voting (created by App)
    in Web3Render (created by App)
    in App
```

**Comment by andytudhope** [comment]
Also, this solution only works with Embark 3.1, as there were a bunch of changes to 3.2.

The `multiple-options` branch in this repo contains fixes for 3.2 functionality, and Iuri is also working on https servers by default for the dev config: https://github.com/embark-framework/embark/issues/940

It means, imo, that we shouldn't merge in current form, but that - whatever happens - we should payout the bounty to @StevenJNPearce, especially if you can get it working with 3.2 😉

**Comment by StevenJNPearce** [comment]
@andytudhope I've fixed the warning about the key prop.

**Comment by andytudhope** [comment]
Perfect - any luck with merging these changes into the `multiple-options` branch and moving over to Embark 3.2? If that works, then I think it's still worth having a `Connect Your Ledger` button in the nav, even if MM supports it too. wdyt @richard-ramos @Graeme-Code?

**Pull request merged**
